<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home</name>
   <tag></tag>
   <elementGuidId>4c6c400e-6e43-4307-b430-8ab411038964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainMenu']/div/a[1]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fa763976-1bfd-4aa7-bb36-0cc06bf2c6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat</value>
      <webElementGuid>d924282a-cb6a-44be-8f5d-80e4f6e58ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sondaggi</value>
      <webElementGuid>223f10fb-5a99-49e9-bd83-fb7a6d1044fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;text-base flex flex-col items-center&quot;]/a[@class=&quot;py-4 group flex flex-col items-center justify-center text-base font-skin-base&quot;]/p[@class=&quot;uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat&quot;]</value>
      <webElementGuid>8f85338e-751a-4435-8d92-2f1a4b9ceb7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainMenu']/div/a[5]/p[2]</value>
      <webElementGuid>d9b1c934-61cc-4cb4-be1b-1f4a0d1a39a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Davide'])[2]/following::p[10]</value>
      <webElementGuid>0d0dd9d5-3595-42e8-a3d7-0632b8068e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/following::p[12]</value>
      <webElementGuid>7c84f414-ccb4-4d3e-a7b7-573b83827fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sondaggi']/parent::*</value>
      <webElementGuid>b49e8fde-586c-4b14-8b74-b93dff7ac53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/p[2]</value>
      <webElementGuid>1dce6ac7-f22f-45f3-8972-e954c01d2236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sondaggi' or . = 'Sondaggi')]</value>
      <webElementGuid>6f3f8631-3b1f-4d98-84d6-ac2ad1d43d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
