<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Gruppi</name>
   <tag></tag>
   <elementGuidId>bd7b4cb3-852b-4cbb-bdda-80754c8b5b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainMenu']/div/a[2]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5ada0a9f-fd7a-4241-aabf-aee10486ea57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat</value>
      <webElementGuid>a1494501-f320-4551-9b98-bbc5edfc22d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gruppi</value>
      <webElementGuid>8a9ae474-c2bf-4af0-962b-39254d4a7b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;text-base flex flex-col items-center&quot;]/a[@class=&quot;py-4 group flex flex-col items-center justify-center text-base font-skin-base&quot;]/p[@class=&quot;uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat&quot;]</value>
      <webElementGuid>fd02a003-d748-4d84-8061-0fb9e50f9851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainMenu']/div/a[2]/p[2]</value>
      <webElementGuid>14a48b16-f331-45bc-bc85-0e345097caba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Davide'])[2]/following::p[4]</value>
      <webElementGuid>27068fe5-ab5c-4d7c-98bf-f9272a915a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/following::p[6]</value>
      <webElementGuid>53596f11-5eff-4156-bfca-6189fcd63d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gruppi']/parent::*</value>
      <webElementGuid>2ff45931-8a0e-4497-8c74-74bd1b83c123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/p[2]</value>
      <webElementGuid>247c986a-e2e9-4be5-bae4-93fbd6d9501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Gruppi' or . = 'Gruppi')]</value>
      <webElementGuid>29056ab5-a3c4-4a36-953f-71975c772de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
