<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Sondaggi</name>
   <tag></tag>
   <elementGuidId>e63cb8b0-5c2f-4d86-a06c-cf983c5319d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainMenu']/div/a[5]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3ab5a85d-7abe-4a11-881a-6ec6b6b549a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat</value>
      <webElementGuid>9132a2da-6f39-4ecb-b7f4-40f44fb4e14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sondaggi</value>
      <webElementGuid>edfadbb6-c769-4bab-a701-7e2ed7fa5a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;text-base flex flex-col items-center&quot;]/a[@class=&quot;py-4 group flex flex-col items-center justify-center text-base font-skin-base&quot;]/p[@class=&quot;uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat&quot;]</value>
      <webElementGuid>55f08dbc-087e-4a42-ba97-2d75b9bc680f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainMenu']/div/a[5]/p[2]</value>
      <webElementGuid>fcd763b2-99b2-41aa-b84c-5caefb06083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Davide'])[2]/following::p[10]</value>
      <webElementGuid>350f2232-b9ce-4e6d-98fd-9372f4e2f7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/following::p[12]</value>
      <webElementGuid>cd22835d-fd5b-441a-a551-d63b066e6ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sondaggi']/parent::*</value>
      <webElementGuid>89314a70-8854-434e-903b-4f3f4062af93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/p[2]</value>
      <webElementGuid>4a47ef53-6f69-4798-81ba-1372cf675adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Sondaggi' or . = 'Sondaggi')]</value>
      <webElementGuid>b2228313-a12a-455e-b0fd-a4881c8d40d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
