<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cliente 2 livello_z-10 absolute top-2 l_e5ebc0</name>
   <tag></tag>
   <elementGuidId>118dbe4a-c064-4afe-a3a8-71d2e8536696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/form/div/div[2]/div/div/div[9]/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f395073-e634-4b1b-b696-70002af81d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-10 absolute top-2 left-2 right-2 bottom-2 group-hover:bg-skin-fillTo label-checked:bg-skin-fillTo opacity-10 cursor-pointer ease-linear transition-all duration-150</value>
      <webElementGuid>39fb99d1-bcf8-4ff3-8385-f307d790d420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/form[1]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;md:w-1/2 w-full flex flex-col h-auto&quot;]/div[@class=&quot;flex flex-col p-4 lg:py-10 lg:px-14 lg:3/5 md:w-5/6 w-full text-md font-regular xl:w-9/12 xl:py-10 xl:px-16&quot;]/div[@class=&quot;space-y-5&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative group rounded-md w-28 mx-2 text-center text-base&quot;]/label[@class=&quot;h-full flex flex-col items-center px-3 py-6 bg-white border rounded-md border-skin-borderBtnRadio&quot;]/div[@class=&quot;z-10 absolute top-2 left-2 right-2 bottom-2 group-hover:bg-skin-fillTo label-checked:bg-skin-fillTo opacity-10 cursor-pointer ease-linear transition-all duration-150&quot;]</value>
      <webElementGuid>76eccd82-f944-4531-8e4e-93d10bd2ec85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div/div[2]/div/div/div[9]/div/label/div</value>
      <webElementGuid>f914c4be-9db5-4206-bba1-2c09de3239a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/label/div</value>
      <webElementGuid>738d0ac6-38ef-47e0-a442-04102dfc0cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
