<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown gruppi</name>
   <tag></tag>
   <elementGuidId>9c7044c8-a728-4197-a3d1-8c724ee76c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-listbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-listbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fac0fe5-0874-4b3e-8955-89f1964ef11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-qr46ko</value>
      <webElementGuid>3ce43e0f-2ccc-41ef-8e90-83891b9de3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>047ebded-523c-43c6-9103-b7e00f5876cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1110ebec-1208-49ec-b36b-de9cba475d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-listbox</value>
      <webElementGuid>16c0d36e-b9d3-49ff-b2a7-0c3237f5d2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimo modificatoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ</value>
      <webElementGuid>7ed785a1-1d6c-482a-a442-73749390e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-listbox&quot;)</value>
      <webElementGuid>719f8f39-029b-43ec-b3c9-b4498cf17072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-listbox']</value>
      <webElementGuid>8ee3e6ce-55f3-440a-9470-377ada6e4cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/form/div/div[3]/div/div/div/div[2]/div</value>
      <webElementGuid>761193a7-7ec7-49bc-b21c-b73fe8553238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca per gruppo'])[1]/following::div[5]</value>
      <webElementGuid>151a58fc-0100-46a2-a258-190c15f71121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtri'])[1]/following::div[20]</value>
      <webElementGuid>66574435-269d-4964-8e01-b159b5b5a83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>6b154d15-c8b5-4611-87ea-34aa01a8265a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-listbox' and (text() = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimo modificatoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ' or . = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimo modificatoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ')]</value>
      <webElementGuid>14b096a3-4e70-4699-b2fc-eb7a5cea06ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
