<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chiudi tabella secondo livello</name>
   <tag></tag>
   <elementGuidId>da8eddb1-c5bd-4f87-bf9c-5e45f4dca0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Linea_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//line[@id = 'Linea_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>38b84154-3532-48f6-95ab-83de21354deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Linea_7</value>
      <webElementGuid>e1469c7e-68cb-481a-b225-b044f8852f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Linea 7</value>
      <webElementGuid>909a98f7-72ec-4f72-993c-f839e84f1006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>476ff4c4-7b35-4b13-95d6-adabd6ac182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>b9ac14ca-cafc-45a5-9b70-6e0a8a67a333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(945.359 34.297)</value>
      <webElementGuid>3441b64f-cbcf-4379-aadb-b5ba85552465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>68af090c-bcf8-463b-8ba0-f77eb2280bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>61037ce3-9903-4352-afd9-6996c2b84e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>39d48c51-5102-44ea-9170-5fa487f3ac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>91edc7b1-5d08-4ea2-958e-364190a24827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b17dea70-b141-4808-8eb6-faad7561cc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Linea_7&quot;)</value>
      <webElementGuid>caf5cc76-f30d-4853-879c-32d0ac7cbf6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//line[@id = 'Linea_7']</value>
      <webElementGuid>bb4deab1-5227-46ed-9c94-f48683a653d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
