<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SI</name>
   <tag></tag>
   <elementGuidId>8254c061-c04d-4b28-9c62-5cf6bad93050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c45315b6-b178-44ea-a590-43651582351d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4555fa32-257e-4516-8c3c-77174a688425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase</value>
      <webElementGuid>9a52d28b-838c-4624-86c6-5e7891c33669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SI</value>
      <webElementGuid>e5b3aec0-9783-497e-918c-7e668f025042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-1&quot;)/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-2xl&quot;]/div[@class=&quot;py-4 w-full flex justify-between px-5 text-skin-textPayBtn text-base font-mediumMontserrat&quot;]/button[@class=&quot;h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase&quot;]</value>
      <webElementGuid>4d4fac86-8d35-40fa-bbc7-1eb9dc4c4e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>e6b3e0ba-40af-454c-94ee-8a5acdb480b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-1']/div/div[2]/div/button</value>
      <webElementGuid>8f1c0ac1-5b51-41e3-b73c-2ac667597058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[2]</value>
      <webElementGuid>8498bb5b-e738-4618-a86c-7388ab6bdd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::button[1]</value>
      <webElementGuid>1357f424-10bb-483e-af9c-4b9aa43f146d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SI']/parent::*</value>
      <webElementGuid>d111c661-6996-49ea-95db-c504c0e8acb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>ac9b4d86-1b8a-48e0-9f1a-d516387e9d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SI' or . = 'SI')]</value>
      <webElementGuid>1af752ed-f4a6-49df-bec5-5dd82b5b5b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
