<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SI</name>
   <tag></tag>
   <elementGuidId>d8ad0297-24dc-4113-afbd-cf4a85a0d346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3684facc-527f-4c66-8d5c-5fde9ee2398e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd3e265c-cf79-4c43-8760-44af1d232db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase</value>
      <webElementGuid>23ff4e93-e9a2-42bd-a7b0-6506a8443f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SI</value>
      <webElementGuid>85820e56-b907-431c-8c63-dc2fc62a68f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-3&quot;)/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-2xl&quot;]/div[@class=&quot;py-4 w-full flex justify-between px-5 text-skin-textPayBtn text-base font-mediumMontserrat&quot;]/button[@class=&quot;h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase&quot;]</value>
      <webElementGuid>8881f455-6316-4a5e-8224-f65b0902defe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>8dd82bc4-df70-42ee-ac18-0e1817d61cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-3']/div/div[2]/div/button</value>
      <webElementGuid>6c42f545-e095-4daa-afad-8b6f7227ab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[2]</value>
      <webElementGuid>fc21e63f-a5e3-45c1-9db2-9b1146d1b3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::button[1]</value>
      <webElementGuid>ff3d2233-a4bd-4a10-95b6-ee5b67daf438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SI']/parent::*</value>
      <webElementGuid>476a4917-5f7b-4fc7-957d-1d95fea7382f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>a0be236d-1410-44d6-993c-8a91eb8c94ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SI' or . = 'SI')]</value>
      <webElementGuid>1a5d9d75-f95f-49d2-8024-5a4c170c2d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
