<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NO</name>
   <tag></tag>
   <elementGuidId>6ca9aa40-f521-4dfa-9f98-642c713e4174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fd2d803-7026-4211-9ba4-54b46209dad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e3be595-11d1-4476-b2f8-d0491225c34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase</value>
      <webElementGuid>32c5e63b-16b2-44cf-882c-394010904aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>fd14da7c-1a63-43d6-bc52-b910d44a4d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-3&quot;)/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-2xl&quot;]/div[@class=&quot;py-4 w-full flex justify-between px-5 text-skin-textPayBtn text-base font-mediumMontserrat&quot;]/button[@class=&quot;h-10 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase&quot;]</value>
      <webElementGuid>15a487d2-43da-48f0-b953-179ff521d499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>861c5490-16ee-4ef3-b104-6db1ca44562d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-3']/div/div[2]/div/button[2]</value>
      <webElementGuid>bf99fe88-2828-4a61-bb08-9a5ff35077f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[1]/following::button[1]</value>
      <webElementGuid>7c5a924f-4eb3-4647-a384-baa2ba43eedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::button[3]</value>
      <webElementGuid>4b790be7-32f5-4a50-887f-6bcd6b336051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO']/parent::*</value>
      <webElementGuid>b5e44665-725a-41aa-86d5-044690212d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button[2]</value>
      <webElementGuid>68e06609-3e9b-45c5-883e-f28120bd4418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'NO' or . = 'NO')]</value>
      <webElementGuid>22032dbb-4fa1-4f7c-a803-2706e79a23a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
