<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_test</name>
   <tag></tag>
   <elementGuidId>faa4e8dd-c2ce-4f60-91b9-1d8526b5000b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Componente_78_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='test1731086875572@example.com'])[1]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>0827c35d-664a-4319-8c1c-6f683663277b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Componente_78_1</value>
      <webElementGuid>2554fccf-714d-4802-8bab-248b6f506e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Componente 78 \u2013 1</value>
      <webElementGuid>ac43c55a-589c-4411-91c3-ebfbf17417db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>90facd48-ac1a-44d0-859e-20ac377a2394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>17.198</value>
      <webElementGuid>5e3c2e79-8141-478a-a319-bfe0e4e055f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17.2</value>
      <webElementGuid>7ff9c895-94dc-4eaf-98e4-e165b6c58afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 17.198 17.2</value>
      <webElementGuid>2683841a-f0b3-475d-9543-35cdbd86c85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block w-5 h-5</value>
      <webElementGuid>d8b8670d-e004-4aa4-9db7-c60c00fa031d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Componente_78_1&quot;)</value>
      <webElementGuid>2dc63ae9-7845-48d4-8b63-4134bdf71222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test1731086875572@example.com'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>70f20e7b-fa53-489a-920b-360757ac4054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tKkSeGrQoh'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>937e42fd-9a4b-4fd3-99f2-6d48834b4e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URtQBU'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>c9505acf-e4e2-49e6-bf5f-641b5a90c826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yyBPrceENT'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>8d849cb5-abda-4342-ac39-4ce7c04ed967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'Componente_78_1']</value>
      <webElementGuid>afe8efce-7bf0-4edb-a7bb-986c1ad34ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
