<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Create RTP</name>
   <tag></tag>
   <elementGuidId>16d59b23-76fb-44a4-9e58-d08e7d17a447</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <authorizationRequest>
      <authorizationInfo>
         <entry>
            <key>bearerToken</key>
            <value>${Token}</value>
         </entry>
      </authorizationInfo>
      <authorizationType>Bearer</authorizationType>
   </authorizationRequest>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;areaCode\&quot;: \&quot;${areaCode}\&quot;,\n  \&quot;agentAreaCode\&quot;: \&quot;${agentAreaCode}\&quot;,\n  \&quot;disposition\&quot;: \&quot;${disposition}\&quot;,\n  \&quot;methods\&quot;: ${methods},\n  \&quot;currency\&quot;: \&quot;${currency}\&quot;,\n  \&quot;language\&quot;: \&quot;${language}\&quot;,\n  \&quot;templates\&quot;: [\n    {\n      \&quot;name\&quot;: \&quot;${name_retail_template}\&quot;,\n      \&quot;channel\&quot;: \&quot;${channel_retail_template}\&quot;,\n      \&quot;recipient\&quot;: \&quot;${recipient_retail_template}\&quot;\n    },\n    {\n      \&quot;name\&quot;: \&quot;${name_agent_template}\&quot;,\n      \&quot;channel\&quot;: \&quot;${channel_agent_template}\&quot;,\n      \&quot;recipient\&quot;: \&quot;${recipient_agent_template}\&quot;\n    }\n  ],\n  \&quot;reason\&quot;: \&quot;${reason}\&quot;,\n  \&quot;expiredAt\&quot;: \&quot;${expiredAt}\&quot;,\n  \&quot;requestCode\&quot;: \&quot;${requestCode}\&quot;,\n  \&quot;payer\&quot;: \&quot;${payer}\&quot;,\n  \&quot;phone\&quot;: \&quot;${phone}\&quot;,\n  \&quot;email\&quot;: \&quot;${email}\&quot;,\n  \&quot;agent\&quot;: \&quot;${agent}\&quot;,\n  \&quot;agentPhone\&quot;: \&quot;${agentPhone}\&quot;,\n  \&quot;agentEmail\&quot;: \&quot;${agentEmail}\&quot;,\n  \&quot;amount\&quot;: \&quot;${amount}\&quot;,\n  \&quot;recurrencyCount\&quot;: \&quot;${recurrencyCount}\&quot;, \n  \&quot;recurrencyDuration\&quot;: \&quot;${recurrencyDuration}\&quot;,\n  \&quot;recurrencyFrequency\&quot;: \&quot;${recurrencyFrequency}\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>3b150580-c4f0-4c33-8a3c-f603ec3ef7dd</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer ${Token}</value>
      <webElementGuid>7561948e-ef33-4678-a36f-235c62ebf8ad</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.5.0</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://server.test.plickup.eu/api/v1/rtps</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.Path</defaultValue>
      <description></description>
      <id>a02a8793-57bc-4db4-bfde-dbcafb3b6801</id>
      <masked>false</masked>
      <name>Environment</name>
   </variables>
   <variables>
      <defaultValue>'eyJraWQiOiI2Q3pTQU9kTkNKejZBNkRLZWZKN0szcVwvUkhPU0NZQ01RYkwxaU1rVjJhST0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI0YmEyNWk1amxlZjRycTM1bDFxNnI0MHU1aSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiaHR0cDpcL1wvcnRwLW0ybS1yZXNvdXJjZVwvYXBpLndyaXRlIiwiYXV0aF90aW1lIjoxNzMyNzI1ODEyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV80NTNMaklrVDAiLCJleHAiOjE3MzI3Mjk0MTIsImlhdCI6MTczMjcyNTgxMiwidmVyc2lvbiI6MiwianRpIjoiZWRhMGUwNjItZTI3MC00NWYyLTk2NDMtMTZkNTM3MDI1MTU4IiwiY2xpZW50X2lkIjoiNGJhMjVpNWpsZWY0cnEzNWwxcTZyNDB1NWkifQ.Uf8rKC_yAyC61N0Z-1QLIma52oPHI8Hv4GfOSNaUdZRBQytZ1zSFVDIeysLai06EpB3v5DNp5tljGGYGeGBL2GxFs5SbdGBDic3F_hJ61MiiAh0wHRa4gWvlF2vLHFeD0LHWVBbE19ne1s9arUfMUstFsR4AsX9F08ZTVE4xNnpvVya7bCNeN3LAdH10DZ9neGGsqPolMQBM3EXmL1JzFOAjMvejJpzByJcnO21B7nUaQ7-okkoqS2NgpWNuWwjqJ5by_J_wu2QkFpXL8ll0g6lakVYC5fluoSQSbS1hzyhf4wC7XCoi5ilfqLMBpjQEt7FgEiL_RbTQegCvL30iFQ'</defaultValue>
      <description></description>
      <id>83b858c5-3cf0-4af9-b7d6-a8583b5b7b62</id>
      <masked>false</masked>
      <name>Token</name>
   </variables>
   <variables>
      <defaultValue>'+39'</defaultValue>
      <description></description>
      <id>2f0f5287-ac52-4b11-b329-94a58de9dc8e</id>
      <masked>false</masked>
      <name>areaCode</name>
   </variables>
   <variables>
      <defaultValue>'+39'</defaultValue>
      <description></description>
      <id>d0907ce4-df21-4e85-8739-461113383b13</id>
      <masked>false</masked>
      <name>agentAreaCode</name>
   </variables>
   <variables>
      <defaultValue>['&quot;PISP&quot;']</defaultValue>
      <description></description>
      <id>88033023-5eee-410e-93f7-e6bdb2c85275</id>
      <masked>false</masked>
      <name>methods</name>
   </variables>
   <variables>
      <defaultValue>'EUR'</defaultValue>
      <description></description>
      <id>abbbcfa6-f903-4cc0-906b-4d15477ec783</id>
      <masked>false</masked>
      <name>currency</name>
   </variables>
   <variables>
      <defaultValue>'it'</defaultValue>
      <description></description>
      <id>470690b7-d0ee-41ef-9cd2-152c66458043</id>
      <masked>false</masked>
      <name>language</name>
   </variables>
   <variables>
      <defaultValue>'causale rtp nuova'</defaultValue>
      <description></description>
      <id>6655f44e-de46-441b-b64b-6c8c0dbcce56</id>
      <masked>false</masked>
      <name>reason</name>
   </variables>
   <variables>
      <defaultValue>'55555'</defaultValue>
      <description></description>
      <id>78617029-2a49-42c5-8e2a-b499e504598f</id>
      <masked>false</masked>
      <name>requestCode</name>
   </variables>
   <variables>
      <defaultValue>'2024-11-18'</defaultValue>
      <description></description>
      <id>effb1472-e807-43a4-b762-65f18b160d01</id>
      <masked>false</masked>
      <name>expiredAt</name>
   </variables>
   <variables>
      <defaultValue>'Paolo Rossi'</defaultValue>
      <description></description>
      <id>a1b09074-a661-497b-a617-9a8d7f5f499c</id>
      <masked>false</masked>
      <name>payer</name>
   </variables>
   <variables>
      <defaultValue>'3493040270'</defaultValue>
      <description></description>
      <id>b3fdc91d-90c5-411f-afe3-3ef8a2dabf23</id>
      <masked>false</masked>
      <name>phone</name>
   </variables>
   <variables>
      <defaultValue>'p.fossarello@quence.it'</defaultValue>
      <description></description>
      <id>ccc3b47d-d8c1-4cb3-9cf7-db0ebbffb0b2</id>
      <masked>false</masked>
      <name>email</name>
   </variables>
   <variables>
      <defaultValue>'Luigi Bianchi'</defaultValue>
      <description></description>
      <id>6eba36d2-4a48-4d1e-80bd-de31bfb4b494</id>
      <masked>false</masked>
      <name>agent</name>
   </variables>
   <variables>
      <defaultValue>'3427484175'</defaultValue>
      <description></description>
      <id>d54aff01-d238-4e4f-a86f-f6b9f2d4dce0</id>
      <masked>false</masked>
      <name>agentPhone</name>
   </variables>
   <variables>
      <defaultValue>'paolofossarello@libero.it'</defaultValue>
      <description></description>
      <id>d6ec7141-4fdc-4a37-8277-6e7e5989890b</id>
      <masked>false</masked>
      <name>agentEmail</name>
   </variables>
   <variables>
      <defaultValue>200.12</defaultValue>
      <description></description>
      <id>90db7996-e087-40d6-8835-5cd2570b3819</id>
      <masked>false</masked>
      <name>amount</name>
   </variables>
   <variables>
      <defaultValue>'SINGLE'</defaultValue>
      <description></description>
      <id>feab2bbb-027a-4b11-9832-d073ce9af963</id>
      <masked>false</masked>
      <name>disposition</name>
   </variables>
   <variables>
      <defaultValue>'MONTHLY'</defaultValue>
      <description></description>
      <id>6ede3102-6e90-4002-be7e-d6dcfd744686</id>
      <masked>false</masked>
      <name>recurrencyFrequency</name>
   </variables>
   <variables>
      <defaultValue>2</defaultValue>
      <description></description>
      <id>8c3051ca-3410-487c-8b31-aa6f74848231</id>
      <masked>false</masked>
      <name>recurrencyDuration</name>
   </variables>
   <variables>
      <defaultValue>12</defaultValue>
      <description></description>
      <id>0bab909a-d8b7-4571-b28b-ef1cd8a49d5d</id>
      <masked>false</masked>
      <name>recurrencyCount</name>
   </variables>
   <variables>
      <defaultValue>'emailRequestRetail'</defaultValue>
      <description></description>
      <id>8bead87a-f31c-467a-9775-c9afac78f19f</id>
      <masked>false</masked>
      <name>name_retail_template</name>
   </variables>
   <variables>
      <defaultValue>'EMAIL'</defaultValue>
      <description></description>
      <id>57412556-a7b9-4fb8-904d-607411f3cc08</id>
      <masked>false</masked>
      <name>channel_retail_template</name>
   </variables>
   <variables>
      <defaultValue>'RETAIL'</defaultValue>
      <description></description>
      <id>ef6b4fc0-5888-4178-97eb-19f915af9c8d</id>
      <masked>false</masked>
      <name>recipient_retail_template</name>
   </variables>
   <variables>
      <defaultValue>'emailRequestAgent'</defaultValue>
      <description></description>
      <id>6e7fc29a-8749-47d9-a8a0-fc6dbe2d39a1</id>
      <masked>false</masked>
      <name>name_agent_template</name>
   </variables>
   <variables>
      <defaultValue>'EMAIL'</defaultValue>
      <description></description>
      <id>0e7adbfd-4cca-44c0-971e-a5c72214762f</id>
      <masked>false</masked>
      <name>channel_agent_template</name>
   </variables>
   <variables>
      <defaultValue>'AGENT'</defaultValue>
      <description></description>
      <id>da01210c-3849-4505-8d06-c36cb297d624</id>
      <masked>false</masked>
      <name>recipient_agent_template</name>
   </variables>
   <variables>
      <defaultValue>true</defaultValue>
      <description></description>
      <id>564e6c09-d917-437c-87fa-2ed23659a6be</id>
      <masked>false</masked>
      <name>attachments_modulary</name>
   </variables>
   <variables>
      <defaultValue>'651ae04cad56da00128daa85'</defaultValue>
      <description></description>
      <id>242edd6a-2cbc-40b1-936d-e36448edbbfe</id>
      <masked>false</masked>
      <name>attachments</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
