<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown gruppi</name>
   <tag></tag>
   <elementGuidId>e22c80c2-d871-4017-9aa3-0316c46b3f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3-listbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-listbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0da3e71-b63a-4fdc-909e-962001acb9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-qr46ko</value>
      <webElementGuid>3bbae75b-c28f-4f25-a036-863fb487c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ba9eeb23-c482-4153-82de-6dcd273fd641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>393e6351-1d52-4d5f-b705-cea498d2c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-3-listbox</value>
      <webElementGuid>50a93f53-90b2-4adb-9a7b-3dc368513a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ</value>
      <webElementGuid>edc90279-a510-42f7-8b63-6173cfc16cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-listbox&quot;)</value>
      <webElementGuid>8aebd91f-9973-4955-9444-469fbf7fabd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-listbox']</value>
      <webElementGuid>5d1d4693-e727-4611-a74f-7239fc501cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div/div[2]/div/div[8]/div/div/div/div[2]/div</value>
      <webElementGuid>2092cd50-7756-4821-9f9a-d0db3e8bd2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gruppo'])[1]/following::div[5]</value>
      <webElementGuid>9b9f9239-6653-4d9d-a463-d46d640d0668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[2]/div</value>
      <webElementGuid>e77048f9-6bec-4e69-908f-48efbd3490a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-3-listbox' and (text() = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ' or . = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ')]</value>
      <webElementGuid>240ac5b1-a98c-41f1-9fd4-f40c705b7aa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
