<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SI</name>
   <tag></tag>
   <elementGuidId>4481d8b1-f53a-4211-8c93-37357a5c898f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4eca5ac9-5474-4208-813d-05b81ce3521f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>852a6c26-0dc0-408b-a7d2-d596b2e3d611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase</value>
      <webElementGuid>52d2435e-a8a3-48a8-a05a-7696374c7d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SI</value>
      <webElementGuid>80afd98b-90bd-42fc-b2eb-45d245a4c691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-3&quot;)/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-2xl&quot;]/div[@class=&quot;py-4 w-full flex justify-between px-5 text-skin-textPayBtn text-base font-mediumMontserrat&quot;]/button[@class=&quot;h-10 mr-4 w-1/2 border border-skin-borderBtn px:4 xl:px-8 focus:outline-none hover:bg-skin-button-accent-hover hover:text-skin-textHover rounded uppercase&quot;]</value>
      <webElementGuid>a1709a83-e7c9-4b1c-8a5d-881d9b75dcad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>c46c42a3-07e1-4498-bde8-b9392386f666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-3']/div/div[2]/div/button</value>
      <webElementGuid>763de7f3-8266-45c3-b8e2-8d9b577c5054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/following::button[2]</value>
      <webElementGuid>5a678620-17ec-4db4-ac61-484a2711c8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementi per pagina'])[1]/following::button[10]</value>
      <webElementGuid>34ac1322-be16-40f6-ae45-4adb15819971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::button[1]</value>
      <webElementGuid>a4f7250e-605e-4a94-9ff3-857449ee1fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SI']/parent::*</value>
      <webElementGuid>d4d336ef-b293-4459-9043-be03b349ae96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/button</value>
      <webElementGuid>6aca1ebb-10a1-4573-926f-52784d36f4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SI' or . = 'SI')]</value>
      <webElementGuid>a344ceb5-ea5a-4f3d-bbfd-48cdbcdffe5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
