<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Filtri_Tracciato_1586</name>
   <tag></tag>
   <elementGuidId>20459ce6-04d9-4e49-a15e-b9fd8638f490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//path[@id = 'Tracciato_1586']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Tracciato_1586</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>ff380c31-8a1f-4804-85fe-81c9518b7e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tracciato_1586</value>
      <webElementGuid>3682a9e8-100c-4cb4-b6ae-f65c4711cfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Tracciato 1586</value>
      <webElementGuid>a63b90cc-6a92-4ca1-81f4-34e0bcfae98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M985.011,138.3l-5.669,5.669-5.669-5.669</value>
      <webElementGuid>e36182a4-ce77-459c-9f6b-35b3cd49bfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-972.967 -137.593)</value>
      <webElementGuid>e5d9c925-12f0-4e26-a304-7ba407c9db23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>3c86b423-9066-4fa4-9557-2182ab58b09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>27410299-5595-42da-ad8c-8abe234e993d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fb6ba278-fbf3-44a6-a50a-341761a07736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>987ebd01-4cc8-492a-be71-2d25f216bcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19684cdf-d470-415e-9856-fe4fdc136c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;-mx-10 -px-10 xl:-mx-20 xl:-px-20 border-b-2 border-skin-borderRowTable font-regularMontserrat text-base&quot;]/div[@class=&quot;mx-auto px-10 xl:px-20 relative&quot;]/div[@class=&quot;flex w-full justify-between px-2 py-4&quot;]/button[1]/svg[1]/path[@id=&quot;Tracciato_1586&quot;]</value>
      <webElementGuid>301146ce-1137-4178-a65c-67281b5cb026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//path[@id = 'Tracciato_1586']</value>
      <webElementGuid>018d3463-094d-498f-850c-253665a5e09b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
