<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown gruppi</name>
   <tag></tag>
   <elementGuidId>2c2b5529-aa64-4744-b7f7-6002a9b974a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-3-listbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-3-listbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77941104-77f1-4249-be7f-ecafca2dbf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-qr46ko</value>
      <webElementGuid>9380039b-3c2c-4438-8432-898cfe9d51fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>193bfda5-d90d-4bc1-b982-fdafbe53bdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82d0e532-3750-45cd-a90a-563988bf3046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-3-listbox</value>
      <webElementGuid>f43ae5c8-c12f-45af-bac3-aaa12ee71e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ</value>
      <webElementGuid>ef278f01-412f-4a2a-b761-1e7dc207c88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-3-listbox&quot;)</value>
      <webElementGuid>3155494a-9c78-4864-9fbc-f0d276e75f7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-3-listbox']</value>
      <webElementGuid>579eec03-02d3-4093-bfec-ed12f11a989d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div/div[2]/div/div[8]/div/div/div/div[2]/div</value>
      <webElementGuid>dca1257f-bf40-44e0-acf5-5c187f256fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gruppo'])[1]/following::div[5]</value>
      <webElementGuid>cba0cd02-e162-45f7-bf12-2b5cc7c45653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div[2]/div</value>
      <webElementGuid>de48ae80-21a7-4953-a09d-a7e94b339ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-3-listbox' and (text() = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ' or . = 'Gabriele GruppotesttestProva-gruppo_1_1Gruppo nuovissimoGruppo - 1Cliente-1 utenzaCliente - 1 UtenteCliente Uno Test1ClienteTest1dfafwsProvaClienteTest2sdfwdqxTRNabmsAhfNGZtThnWuaOrAsadasdClienteTest1swKjFZVtIIvRQCXiofmjHWjaTYqyWuQarvEbwfgxPYQTHVlGqNJtEqLSosHyIIMgKTZ')]</value>
      <webElementGuid>a58f4e00-7770-4939-bc04-c0989e2c567a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
