<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gestione utenti</name>
   <tag></tag>
   <elementGuidId>dc17ae75-e119-4f9e-9984-edd276ea79d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.border.border-skin-borderBtnRadio.flex.h-24.items-center.z-30.px-5.text-skin-base.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bf60097-45d2-4fa5-bc09-7fa81d6d2b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-skin-borderBtnRadio flex  h-24 items-center z-30 px-5 text-skin-base cursor-pointer</value>
      <webElementGuid>a45d9ad5-4fe7-49f2-8730-b810391028c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gestione utenti</value>
      <webElementGuid>ee3a7a07-c5b0-4c7b-b082-5b53b1de514f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;flex items-start justify-center px-4 sm:px-6 lg:px-8&quot;]/div[@class=&quot;max-w-sm w-full&quot;]/div[@class=&quot;space-y-8 p-5 text-center&quot;]/div[@class=&quot;relative my-3 group&quot;]/div[@class=&quot;border border-skin-borderBtnRadio flex  h-24 items-center z-30 px-5 text-skin-base cursor-pointer&quot;]</value>
      <webElementGuid>6cf66777-7148-4796-ab5a-deab583c2625</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div[2]/div/div</value>
      <webElementGuid>0d1e7da6-6234-4fd7-924c-e83cfc17e83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quence'])[1]/following::div[7]</value>
      <webElementGuid>6082bc99-6cdb-449b-ad03-99787c5e0084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::div[8]</value>
      <webElementGuid>0f1ca416-4673-448c-bc2a-31502f7e2a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>70ac162a-5cf7-4890-8cf0-38c78d461b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gestione utenti' or . = 'Gestione utenti')]</value>
      <webElementGuid>5aaa2103-0904-469a-8c5f-794c331f6295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
