<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Plick</name>
   <tag></tag>
   <elementGuidId>15cf8082-2322-4a3b-8e60-21b8b838e036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/form/div/div[2]/div/div[7]/div[1]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.h-full.flex.flex-col.items-center.px-3.py-6.bg-white.border.rounded-md.border-skin-borderBtnRadio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7271ab02-8758-4307-a643-382491f516fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-full flex flex-col items-center px-3 py-6 bg-white border rounded-md border-skin-borderBtnRadio</value>
      <webElementGuid>124cc330-a244-41e8-bd7e-54de74212648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plick</value>
      <webElementGuid>6fca9f6f-cdf3-4597-a8b5-a23a94099306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/form[1]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;md:w-1/2 w-full flex flex-col text-lg font-mediumMontserrat font-skin-base&quot;]/div[@class=&quot;flex space-y-6 flex-col p-4 lg:py-10 lg:px-14 lg:3/5 md:w-5/6 w-full text-base font-regular xl:w-9/12 xl:py-10 xl:px-16&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative group rounded-md w-28 mx-2 text-center text-base&quot;]/label[@class=&quot;h-full flex flex-col items-center px-3 py-6 bg-white border rounded-md border-skin-borderBtnRadio&quot;]</value>
      <webElementGuid>c9084b9b-0818-48b6-b827-11ebb30f4c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div/div[2]/div/div[7]/div/label</value>
      <webElementGuid>7d356cf3-c83a-40b0-8468-5614aa5fad76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deve avere una lunghezza minima di 8 caratteri e massima di 128 caratteri'])[1]/following::label[1]</value>
      <webElementGuid>9aac668a-2aa1-4d45-a8c0-a6b5439d87b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::label[3]</value>
      <webElementGuid>5e4c3810-f353-452c-b712-d8e12a913110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::label[3]</value>
      <webElementGuid>4cf809be-ea1a-46a1-927a-7b54986d5b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/label</value>
      <webElementGuid>3fc1897d-d4ed-4db6-9ea2-70380e2d29c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Plick' or . = 'Plick')]</value>
      <webElementGuid>1ba1486d-319a-4619-b2fd-3e188b9cf5d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
