<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aggiorna</name>
   <tag></tag>
   <elementGuidId>36e0f78e-b8af-4c69-89b2-69dc1a096661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'createNewCustomer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createNewCustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='createNewCustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createNewCustomer</value>
      <webElementGuid>8942ddca-9dce-4418-921b-f8d73dba235c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='createNewCustomer']</value>
      <webElementGuid>a866697f-7f31-4019-acfa-7289383e1f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div/div[2]/div/div/div[10]/button</value>
      <webElementGuid>e2b908a4-5eb9-43e3-a5f9-ee6fa41b0f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente 2° livello'])[2]/following::button[1]</value>
      <webElementGuid>27a2d0e0-efd1-4a11-be86-26f926616ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[2]/following::button[2]</value>
      <webElementGuid>84f2eab9-ec67-439c-9bec-ecdf945cfd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aggiorna']/parent::*</value>
      <webElementGuid>c65df79c-ab71-43ee-a18f-73b74a0d0b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button</value>
      <webElementGuid>1df0d1de-0b0b-484e-b964-f34cc26afea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'createNewCustomer' and @type = 'submit' and (text() = 'Aggiorna' or . = 'Aggiorna')]</value>
      <webElementGuid>3a8ba19e-1228-4f89-9a08-51456253f6d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
