<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Clienti</name>
   <tag></tag>
   <elementGuidId>d6e88303-a9e0-4de8-b06c-f4fa639ab4e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainMenu']/div/a[3]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b8b48ada-511d-46f6-ace8-5d746c474f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat</value>
      <webElementGuid>83958c43-059b-40b0-9f46-8742ad8cdb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clienti</value>
      <webElementGuid>f1e4776c-38e1-4538-b1f3-9ac69b775c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainMenu&quot;)/div[@class=&quot;text-base flex flex-col items-center&quot;]/a[@class=&quot;py-4 group flex flex-col items-center justify-center text-base font-skin-base&quot;]/p[@class=&quot;uppercase transition-transform ease-out transform group-hover:translate-y-2 group-hover:font-medium duration-200
                    font-regularMontserrat&quot;]</value>
      <webElementGuid>49cd270c-56fa-4085-94a9-4cb29ff4e9aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainMenu']/div/a[3]/p[2]</value>
      <webElementGuid>38ad4654-6d1d-4325-9964-951b8fe9eacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quence'])[2]/following::p[6]</value>
      <webElementGuid>9d32fff0-73b8-41a5-b544-855498eab19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::p[7]</value>
      <webElementGuid>80f712e5-7478-4752-a7b8-7763bf4f48a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clienti']/parent::*</value>
      <webElementGuid>4a7524be-5a96-4188-8379-3f59eb1004c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/p[2]</value>
      <webElementGuid>c98a2409-08bc-43cb-82c9-555dc9b59b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Clienti' or . = 'Clienti')]</value>
      <webElementGuid>191a00e4-2335-4483-9c49-d41ab8c1e2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
