<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_clienti</name>
   <tag></tag>
   <elementGuidId>677b7afa-9d8f-4889-995a-d7b208f81442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.py-2.align-middle.inline-block.min-w-full.relative</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dec813c2-06a4-47f6-b91e-6b0bff3d8c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 align-middle inline-block min-w-full relative</value>
      <webElementGuid>e6458b36-6364-493a-b804-e03cbfca18f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NomeP.IVAEmailTelefonoLivelloFastBank1234567davide.casadei+customer_first@txt.fastcode.it+39 340 60570961 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaArmenioPironearme@yopmail.com+39 329 87987981 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaEremoRemotoere@yopmail.com+39 329 78561241 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaPaolono Aridone9898pa@yopmail.com+39 329 92657771 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaSalvatore test123456sasà@mobilesoft.it38987699291 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloElimina</value>
      <webElementGuid>e693284e-d852-4d0d-a118-c6974153a355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;mt-2 flex flex-col&quot;]/div[@class=&quot;overflow-x-auto px-1 py-4&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full relative&quot;]</value>
      <webElementGuid>b3f288e8-66ac-451b-bfd5-a08bb18a3f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div</value>
      <webElementGuid>abef9fbf-cc71-494d-9b0c-01f940ea814a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca cliente per nome'])[1]/following::div[4]</value>
      <webElementGuid>5ab88461-572e-4e7f-9521-d274418dc9e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtri'])[1]/following::div[7]</value>
      <webElementGuid>a6d8e0aa-81ae-4b03-9016-88f5ffcce3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>a573ccf7-3de2-4e43-bc33-d940b22e53b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NomeP.IVAEmailTelefonoLivelloFastBank1234567davide.casadei+customer_first@txt.fastcode.it+39 340 60570961 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaArmenioPironearme@yopmail.com+39 329 87987981 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaEremoRemotoere@yopmail.com+39 329 78561241 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaPaolono Aridone9898pa@yopmail.com+39 329 92657771 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaSalvatore test123456sasà@mobilesoft.it38987699291 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloElimina' or . = 'NomeP.IVAEmailTelefonoLivelloFastBank1234567davide.casadei+customer_first@txt.fastcode.it+39 340 60570961 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaArmenioPironearme@yopmail.com+39 329 87987981 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaEremoRemotoere@yopmail.com+39 329 78561241 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaPaolono Aridone9898pa@yopmail.com+39 329 92657771 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloEliminaSalvatore test123456sasà@mobilesoft.it38987699291 °ModificaAbilitazioniImporta fileTemplateAggiungi 2° livelloClienti 2° livelloElimina')]</value>
      <webElementGuid>12f90f72-d82a-417a-ae51-7f5547b1950a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
