<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Id_pratica</name>
   <tag></tag>
   <elementGuidId>d071b5b9-0f55-4357-a97b-df6928a250eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-base.font-regularMontserrat.text-skin-base.w-full.break-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class, 'flex') and contains(@class, 'justify-around')]//label[text()='Id']/following::p[contains(@class, 'text-base')][1]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9baf9d6f-db69-42d2-ac53-8171bda540a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-regularMontserrat text-skin-base w-full break-all</value>
      <webElementGuid>b50d6929-ab21-40d6-96a1-d6e4128f62de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 31/12/2024</value>
      <webElementGuid>864a6de0-33a3-4c7d-8274-1d3983199860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;mt-2 flex flex-col&quot;]/div[@class=&quot;overflow-x-auto px-1 py-4&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full relative&quot;]/table[@class=&quot;min-w-full table-auto px-2 text-skin-base relative&quot;]/tbody[@class=&quot;bg-white divide-y divide-skin-borderRowTable border border-skin-borderRowTable&quot;]/tr[@class=&quot;container&quot;]/td[1]/div[@class=&quot;mx-auto relative&quot;]/div[@class=&quot;pt-4&quot;]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;sm:w-1/3 bg-skin-bgDefault&quot;]/div[@class=&quot;h-full px-8 py-2 flex flex-col justify-around bg-row-amount bg-no-repeat bg-bottom-custom bg-contain bg-16&quot;]/div[@class=&quot;pb-2&quot;]/p[@class=&quot;text-base font-regularMontserrat text-skin-base w-full break-all&quot;]</value>
      <webElementGuid>b2a327a3-5b65-481f-828b-f4f417acc195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div/table/tbody/tr[2]/td/div/div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>f9973c23-10b9-4e52-94a7-99bed932707a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scadenza'])[2]/following::p[1]</value>
      <webElementGuid>7b8df523-576d-4896-bd2a-8c4a4e7205d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importo'])[3]/following::p[2]</value>
      <webElementGuid>20dd587b-7514-496e-a707-b32071b98cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causale'])[2]/preceding::p[1]</value>
      <webElementGuid>8d8fd376-5844-4d82-911b-8518e08d6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id'])[1]/preceding::p[2]</value>
      <webElementGuid>49e84a03-824a-493d-9e2a-aec8e41d3854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>37ba400d-a56b-4676-b419-3a2297871486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' 31/12/2024' or . = ' 31/12/2024')]</value>
      <webElementGuid>3174249e-f406-4541-addc-719749eb20d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
