<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Elimina</name>
   <tag></tag>
   <elementGuidId>6c1bacdf-3932-4f19-a204-6b987600773f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.border-t.border-skin-borderBtnRadio.mt-8.min-h-32.relative > div.mt-2.flex.flex-col > div.overflow-x-auto.px-1.py-4 > div.py-2.align-middle.inline-block.min-w-full.relative > table.min-w-full.table-auto.px-2.text-skin-base.relative > tbody.bg-white.divide-y.divide-skin-borderRowTable.border.border-skin-borderRowTable > tr.h-14 > td.px-3.py-1.whitespace-nowrap.text-skin-base.font-regularMontserrat.text-base > div.flex.justify-end.items-center.pr-5 > button.relative.group.pl-4 > div.py-2.inline-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[4]/div[2]/div/div/table/tbody/tr/td[7]/div/button/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>425bbfe2-2d3d-41f0-a17b-1357b6544b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 inline-block</value>
      <webElementGuid>d50cebc5-677e-4832-9dbb-a82f40d5d06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Elimina</value>
      <webElementGuid>9bee2e2b-adbd-4144-bd00-05457c20c6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;border-t border-skin-borderBtnRadio mt-8 min-h-32 relative&quot;]/div[@class=&quot;mt-2 flex flex-col&quot;]/div[@class=&quot;overflow-x-auto px-1 py-4&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full relative&quot;]/table[@class=&quot;min-w-full table-auto px-2 text-skin-base relative&quot;]/tbody[@class=&quot;bg-white divide-y divide-skin-borderRowTable border border-skin-borderRowTable&quot;]/tr[@class=&quot;h-14&quot;]/td[@class=&quot;px-3 py-1 whitespace-nowrap text-skin-base font-regularMontserrat text-base&quot;]/div[@class=&quot;flex justify-end items-center pr-5&quot;]/button[@class=&quot;relative group pl-4&quot;]/div[@class=&quot;py-2 inline-block&quot;]</value>
      <webElementGuid>9ee1d835-0397-499a-8dac-f5138aa98849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[4]/div[2]/div/div/table/tbody/tr/td[7]/div/button/div</value>
      <webElementGuid>9e56548d-87a6-4377-a37b-a215de517e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JIhThl'])[2]/following::div[11]</value>
      <webElementGuid>2274315c-3d2b-4934-9ef9-396fba0e9f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test1731499210513@example.com'])[1]/following::div[11]</value>
      <webElementGuid>eed438f0-4752-4aa7-8565-c15ec7fa5093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementi per pagina'])[2]/preceding::div[3]</value>
      <webElementGuid>bd451437-9266-45fb-ab8c-aac1e472219e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::div[5]</value>
      <webElementGuid>a54010de-8f0c-42a3-9e67-940f3b94cd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/button/div</value>
      <webElementGuid>4d9f488f-b8f1-4db3-b241-418e3ff65845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Elimina' or . = 'Elimina')]</value>
      <webElementGuid>76ad02d3-3a09-4866-94eb-b4c1ba701032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
