<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Campo ricerca Lista clienti</name>
   <tag></tag>
   <elementGuidId>4e4fec16-d8ac-4a3b-8aa7-46969899d5f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='rdl-list-box rdl-available']//div[@class='rdl-filter-container']//input[contains(@class, 'rdl-filter')]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rdl-vDxxqNiQo3P3zRorfXVyD-filter-available</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Filter available&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49007462-a700-46b0-ad39-0e99700bac9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-filter</value>
      <webElementGuid>12888354-424f-482b-808f-dd7f7f64254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>available</value>
      <webElementGuid>33399243-3b2d-49c6-866e-51e9fbd03164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-vDxxqNiQo3P3zRorfXVyD-filter-available</value>
      <webElementGuid>3d10aa11-0e9e-429d-8354-b4edb6272a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cerca cliente</value>
      <webElementGuid>6b7fd0f5-9aa5-4c64-8f6d-b9d0ccd81f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c85ba12b-3f5a-466b-8902-d2a3c0f917a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-vDxxqNiQo3P3zRorfXVyD-filter-available&quot;)</value>
      <webElementGuid>0ac48063-9e58-4079-b883-699129f641af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdl-vDxxqNiQo3P3zRorfXVyD-filter-available']</value>
      <webElementGuid>f501c4fb-62d8-4212-919f-d3649e075449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-vDxxqNiQo3P3zRorfXVyD']/div/div/input</value>
      <webElementGuid>e93bd31c-0e3b-4a45-88ee-50c50e145205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>f0329b5a-885f-4d0b-8088-d84a04817db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdl-vDxxqNiQo3P3zRorfXVyD-filter-available' and @placeholder = 'Cerca cliente' and @type = 'text']</value>
      <webElementGuid>146cbec3-61f3-432b-bb4e-f3e9b67de3a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
