<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>X_chiudi Configurazioni callback_1</name>
   <tag></tag>
   <elementGuidId>7ae4fa84-e0ee-49b2-a6c7-cb28bee52984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Linea_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//line[@id = 'Linea_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>6e944974-8d70-426d-a148-7ecfd1e26511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Linea_7</value>
      <webElementGuid>383c6c4c-851f-46ef-b6c3-7f4cca745bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Linea 7</value>
      <webElementGuid>7910d9fd-1e56-4bd0-a550-f6986004d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>6330287d-a3ef-45e5-9773-6da12192d86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>af04aa17-0052-41be-9f67-cafd5ebe85ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(945.359 34.297)</value>
      <webElementGuid>bd43dca8-4b51-4b51-8fd8-e8f419da10c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5a40921f-a365-47f2-885a-5cb78a327be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>16f85152-a416-40bf-86b7-db6b2766c8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>2b3a0aad-30c2-4667-b23c-f09833a21d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>6732e0b5-dae3-4e21-81f6-4801afdae9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>955fe803-413d-4de4-8b1e-75e13521b2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-6&quot;)/div[@class=&quot;min-h-screen px-4 text-center&quot;]/div[@class=&quot;space-y-6 inline-block w-full max-w-md p-6 my-8 overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl rounded-md&quot;]/div[@class=&quot;flex items-center justify-between&quot;]/svg[@class=&quot;w-4 h-4 cursor-pointer&quot;]/g[@id=&quot;Raggruppa_44&quot;]/line[@id=&quot;Linea_7&quot;]</value>
      <webElementGuid>866e7b75-f127-4b32-8d6e-dd00e975cf3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//line[@id = 'Linea_7']</value>
      <webElementGuid>ad826f81-de21-45e2-acd9-40fd99eff08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
