<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>X_chiudi Configurazioni exit url_1</name>
   <tag></tag>
   <elementGuidId>a449272a-76ac-4476-9b19-75d4842b2439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Linea_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//line[@id = 'Linea_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>078cdae2-c88f-4e63-9c3a-938441c9bac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Linea_7</value>
      <webElementGuid>d86ec5d7-ebd9-458f-bee2-f06186e5193f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Linea 7</value>
      <webElementGuid>3579e2b5-60cb-422a-9d65-238858241f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>93f89dc1-e6f4-441c-a63e-4b42c0a17eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>094b9232-48f3-497c-9c09-79ad2029cd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(945.359 34.297)</value>
      <webElementGuid>28d4fde9-3494-4268-a3ab-43ed2baacc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9f9411ec-6c9e-4a7d-b849-c9c9601ee619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>a442b33d-2fb1-4f7d-9bbf-4ed0824c2615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>43fa9ced-a76a-4855-9a9e-f74856ba0f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>84fa1c44-8e87-4206-a8da-28d0c29d2776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3eb74f58-6e2e-49d6-a4e8-b9339a16d389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Linea_7&quot;)</value>
      <webElementGuid>91c520b4-fa8f-4784-b81b-f69d4d6e8661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//line[@id = 'Linea_7']</value>
      <webElementGuid>240aecb9-db94-40bd-9b55-48751a58e155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
