<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>X_chiudi Configurazioni license_1</name>
   <tag></tag>
   <elementGuidId>a2a24e98-bf41-4cb1-b4bc-bad78279c162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Linea_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//line[@id = 'Linea_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>a6c1fe05-c6ea-43a3-aac5-8307334871bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Linea_7</value>
      <webElementGuid>9244e10e-f3d2-4cd2-9e5a-f922fe83bd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Linea 7</value>
      <webElementGuid>c1c37641-4adc-45b8-9284-14f73e079d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>f79c8c15-e1ad-4541-b99d-72f327b36238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>23b617ca-68c9-4704-934d-84caf7f16150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(945.359 34.297)</value>
      <webElementGuid>6d494ec3-3345-42c1-8b50-6cbf733028d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f926b8c6-44a0-45fb-bb31-c97fb29416c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>9277ca3f-2ea1-489c-952d-394afa81302e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>e71d7da5-69ec-4bea-b584-d08d712d1ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>4cff3049-c7f1-4958-b507-49dfba7dc195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f292aa24-a202-4655-8e3f-6391c1ad9f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Linea_7&quot;)</value>
      <webElementGuid>6be26c56-494e-4691-aaf4-d50e052e96ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//line[@id = 'Linea_7']</value>
      <webElementGuid>f8f3c3a3-ed19-4b17-8363-6e975118c222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
