<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1</name>
   <tag></tag>
   <elementGuidId>1b915a2e-883d-4d7a-b1a2-c1ac7bff2c07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div[2]/nav[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mx-1.inline-flex.justify-center.items-center.h-6.w-9.text-xs.font-regularMontserrat.bg-skin-button-muted.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64eeb2d6-d767-480f-a14b-f17374b50521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-1 inline-flex justify-center items-center h-6 w-9 text-xs font-regularMontserrat bg-skin-button-muted text-white</value>
      <webElementGuid>c0314138-8438-403f-9ed6-c914c061bbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>10c81cb7-7643-403d-9e44-62ad7d6dc9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;mt-2 flex flex-col&quot;]/div[@class=&quot;py-4 text-right flex space-x-12 justify-end items-center&quot;]/nav[@class=&quot;relative z-0 inline-flex&quot;]/button[@class=&quot;mx-1 inline-flex justify-center items-center h-6 w-9 text-xs font-regularMontserrat bg-skin-button-muted text-white&quot;]</value>
      <webElementGuid>5c8659b2-65f7-44ad-ba06-3509bdd41c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div[2]/nav[2]/button[2]</value>
      <webElementGuid>a8b0cc8a-5f42-4f37-88b1-7eaacbef8883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementi per pagina'])[1]/following::button[2]</value>
      <webElementGuid>11528ac6-9d1f-48c4-b7e5-81c090763ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sasà@mobilesoft.it'])[1]/following::button[9]</value>
      <webElementGuid>36bbd664-032a-47d5-a818-06aba3420396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::button[6]</value>
      <webElementGuid>8b786647-3c30-4fc7-9e2f-5ba03f62e494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/button[2]</value>
      <webElementGuid>fc75950a-03ed-4441-b725-652333ac4df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '1' or . = '1')]</value>
      <webElementGuid>27a0a6c0-265a-4f71-9346-04cf1d7b89e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
