<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__cm-activeLine cm-line_SMS</name>
   <tag></tag>
   <elementGuidId>ed0cc4ad-a0a7-4340-8927-6510e5d24785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/form/div[4]/div[2]/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cm-activeLine.cm-line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1426aed7-d9f1-41a7-9efa-9433fbc546be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cm-activeLine cm-line</value>
      <webElementGuid>c78d7ab8-7af5-49e7-8ce1-fc048fc688ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/form[@class=&quot;space-y-14&quot;]/div[4]/div[@class=&quot;cm-theme my-4&quot;]/div[@class=&quot;cm-editor cm-focused ͼ1 ͼ3 ͼ4 ͼ18 ͼo&quot;]/div[@class=&quot;cm-scroller&quot;]/div[@class=&quot;cm-content&quot;]/div[@class=&quot;cm-activeLine cm-line&quot;]</value>
      <webElementGuid>adaea8db-b805-4a5a-9cc8-7a6e866cc09a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/form/div[4]/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>b732f851-4256-4f00-a369-03eed9948fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::div[3]</value>
      <webElementGuid>4106aae1-e738-4e53-9312-64c18cfe6942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FORMAT'])[1]/following::div[13]</value>
      <webElementGuid>2e4aaa33-830e-4c2a-8cdd-a26a7ffe0a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salva template'])[1]/preceding::div[4]</value>
      <webElementGuid>d663f9f0-751e-450b-ade6-bb6194813d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::div[8]</value>
      <webElementGuid>453923e2-8352-4419-98cb-f6afd78fcd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>72c67057-617c-44e3-9f5e-d49e049be861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
