<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gruppo eliminatoOperazione eseguita con successo</name>
   <tag></tag>
   <elementGuidId>26d99565-9572-4b64-975e-75379a2cebd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.flex-col.flex-1.px-2.space-y-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3b6ge1k']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2429b52e-9e1b-4852-9bc2-233ebcd5d957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col flex-1 px-2 space-y-1</value>
      <webElementGuid>e68ccb44-4403-4806-8aa9-ef471f1e1e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gruppo eliminatoOperazione eseguita con successo</value>
      <webElementGuid>a8553dd5-4ce4-4ba2-b9c1-c0f87529db2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3b6ge1k&quot;)/div[@class=&quot;Toastify__toast-body p-0 m-0&quot;]/div[1]/div[@class=&quot;flex space-x-4 w-auto&quot;]/div[@class=&quot;flex flex-col flex-1 px-2 space-y-1&quot;]</value>
      <webElementGuid>cb2186fb-457a-4889-94af-0c2796ad1a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3b6ge1k']/div/div/div/div</value>
      <webElementGuid>85675b51-6beb-4b1e-b390-778f877eaee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementi per pagina'])[1]/following::div[8]</value>
      <webElementGuid>213131f6-26db-4d6f-9ca9-ebcd2b5d3156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dfwdq'])[1]/following::div[19]</value>
      <webElementGuid>054aeb8a-691d-4044-990a-ea5d883a7f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div</value>
      <webElementGuid>d3411df7-aa69-4091-acf6-ffe9e66d9996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gruppo eliminatoOperazione eseguita con successo' or . = 'Gruppo eliminatoOperazione eseguita con successo')]</value>
      <webElementGuid>152a1a23-7136-4f99-bf95-5cb0f92e25a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
