<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter available_rdl-i2Btn5yl189MsEs2l0ECu-filter-available</name>
   <tag></tag>
   <elementGuidId>e488aa66-89c2-4e3c-8705-c9ae068ce1f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-i2Btn5yl189MsEs2l0ECu-filter-available</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@data-key='selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27df386a-b782-48f9-bdc1-d0b5622b69b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-filter</value>
      <webElementGuid>ee44f3d8-d187-4bfe-8310-b2ead0b5b68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>available</value>
      <webElementGuid>e9530877-32cb-4e26-be5a-44dcfbcffe9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-i2Btn5yl189MsEs2l0ECu-filter-available</value>
      <webElementGuid>3605161f-81f3-4501-a172-7990a4225898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cerca cliente</value>
      <webElementGuid>3828f3ec-205c-49d4-bfcb-34376e4203c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f654e1d1-8ef0-4266-9b6b-675ccb1fc040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Antonio Marco</value>
      <webElementGuid>82bd5185-e781-43c6-b48f-42a9d50356a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-i2Btn5yl189MsEs2l0ECu-filter-available&quot;)</value>
      <webElementGuid>a41e4ef1-8202-45a9-bb3f-f55f66a8c966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdl-i2Btn5yl189MsEs2l0ECu-filter-available']</value>
      <webElementGuid>70698a0a-8410-4682-88ed-a82388f0e442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-i2Btn5yl189MsEs2l0ECu']/div/div/input</value>
      <webElementGuid>652a6a91-d2b6-47c0-98e7-23b43d903359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>fd03363d-1135-4caf-b87c-f0fb5774d911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdl-i2Btn5yl189MsEs2l0ECu-filter-available' and @placeholder = 'Cerca cliente' and @type = 'text']</value>
      <webElementGuid>afa76355-d6da-4a76-a027-0d078340cf79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
