<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter available_rdl-fElmddpYC6C1-Q1E_baeaf8</name>
   <tag></tag>
   <elementGuidId>bf83fb6f-37cd-435c-9387-ef1d4068f6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-fElmddpYC6C1-Q1EwL0so-filter-available</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='rdl-filter'][@id='rdl-sA12k5lYnGu90vXRgKrQb-filter-available']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>423f009c-bb39-485e-bfc7-00429b709e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-filter</value>
      <webElementGuid>dd43175f-1a52-4f8e-bded-390dd7467e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>available</value>
      <webElementGuid>d6a49cc6-a4c4-4e7d-90e2-0935c163b8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-fElmddpYC6C1-Q1EwL0so-filter-available</value>
      <webElementGuid>ea72e81c-943c-4a9f-b75f-16c81756a7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cerca cliente</value>
      <webElementGuid>781288fe-930b-4f67-92f0-fb8c54080b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8b63e8b-9115-444c-811b-ef3736985de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-fElmddpYC6C1-Q1EwL0so-filter-available&quot;)</value>
      <webElementGuid>e5571a63-a04b-4e66-9f10-b0a3b0ef3c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rdl-fElmddpYC6C1-Q1EwL0so-filter-available']</value>
      <webElementGuid>3b8d3825-ac74-4584-bf11-a04b73dad3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-fElmddpYC6C1-Q1EwL0so']/div/div/input</value>
      <webElementGuid>33b88ac7-87b8-4c93-92e5-2847a721d970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>51624c4a-c0d5-4ac0-8492-03f340167963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'rdl-fElmddpYC6C1-Q1EwL0so-filter-available' and @placeholder = 'Cerca cliente' and @type = 'text']</value>
      <webElementGuid>7d2b2a3e-b683-4f33-85a0-5f79596fcb62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
