<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line_Davide_Linea_6</name>
   <tag></tag>
   <elementGuidId>ec29b2af-70b3-4edc-8e94-b3fecd174b09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Linea_6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//line[@id = 'Linea_6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>494f5603-ef4c-41cf-a552-9ab181f67868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Linea_6</value>
      <webElementGuid>8e45e711-cf1f-4799-80ae-5c926a567f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Linea 6</value>
      <webElementGuid>29ac8d86-e7b4-48e6-a525-bd6b45844c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>499d9865-eb7b-43cd-8e2a-595e069cfca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>15.999</value>
      <webElementGuid>7e36cc89-416f-496d-96d1-2b151e892e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(945.359 34.297)</value>
      <webElementGuid>b1265112-bbfe-4c71-a66d-b8610cb445c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ae4a123b-d5f3-44d4-b3ff-3c340eddef04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#38719a</value>
      <webElementGuid>7889532a-7702-4a5f-b510-57747ded34fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>dba05fb5-0ef5-4b04-a8d7-1baf5d190afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>03a1069b-9adc-49f2-9b85-1a30d92e159a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>976bd2e6-7da1-4367-9c0f-0ac9016b821a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Linea_6&quot;)</value>
      <webElementGuid>6bc0516f-77a7-4389-871e-86109561716d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//line[@id = 'Linea_6']</value>
      <webElementGuid>fa264b9b-9c71-4002-b7df-d462479643d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
