<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_adadad</name>
   <tag></tag>
   <elementGuidId>4bb72a99-715e-44ae-b1a8-c3de2d0e54b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@id='rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a9691584-976d-4ff2-856f-2ffae02caed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-real-value</name>
      <type>Main</type>
      <value>&quot;61f2c730c12c8a00125307a1&quot;</value>
      <webElementGuid>c313a246-94bd-434b-8e82-68de2d1f1c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1</value>
      <webElementGuid>9e7863e9-3d06-437c-9468-b0253d9b3f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>61f2c730c12c8a00125307a1</value>
      <webElementGuid>ab79f8af-f985-4a1f-8fea-66dc519ec435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adadad</value>
      <webElementGuid>c175defb-e8f8-43d3-a7a7-db4b93bd3d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1&quot;)</value>
      <webElementGuid>430320b6-d4d0-44ab-a8de-c1e74cbe3d1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1']</value>
      <webElementGuid>d46ede2a-3905-4a92-bc81-110af6201e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-bGzuTas50iaUSG1dKhIKQ-available']/option</value>
      <webElementGuid>4ef9e3bd-0610-46d6-a473-d30ef741d3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter available'])[1]/following::option[1]</value>
      <webElementGuid>f62cbd0a-fa04-456e-b4c8-8fd8680541b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::option[1]</value>
      <webElementGuid>1a18e2fc-07bd-40cf-9069-0de25a01c20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/preceding::option[163]</value>
      <webElementGuid>b9606a52-8fcd-4f6a-a5f4-0f783a0918d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/preceding::option[163]</value>
      <webElementGuid>c8d6d1b8-e5a2-4c06-bc09-422186357061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adadad']/parent::*</value>
      <webElementGuid>a53d8677-ca6b-42b1-91cb-bff8e7bc0f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select/option</value>
      <webElementGuid>54f07241-c924-4d5b-b358-0f5af5aa2b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-bGzuTas50iaUSG1dKhIKQ-option-61f2c730c12c8a00125307a1' and (text() = 'adadad' or . = 'adadad')]</value>
      <webElementGuid>c54dc15a-5a50-421d-9eb8-77ac86d11606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
