<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Agenzia test Sekurest</name>
   <tag></tag>
   <elementGuidId>0e682343-533b-446d-bdcd-5b2cae5c09b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[@id='rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7a21a0af-ade1-4791-8697-12c48d33b61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa39d294-2765-4fa8-8241-65b291ac54bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-real-value</name>
      <type>Main</type>
      <value>&quot;65a662ea9bb42500122eec55&quot;</value>
      <webElementGuid>aecb1e85-a46e-4ddc-bf09-d60b072404c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55</value>
      <webElementGuid>4bad0a11-268d-40b7-99e1-db03d1470301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>65a662ea9bb42500122eec55</value>
      <webElementGuid>5e7d56b1-c6e5-4e4d-b56d-e2005ad0b83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenzia test Sekurest</value>
      <webElementGuid>10e3e93f-9d84-4e0c-b61f-df744ffda2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55&quot;)</value>
      <webElementGuid>ad07f9eb-6891-42ae-9e68-188f2d0b4c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55']</value>
      <webElementGuid>66dd9eaf-406b-44c6-aa47-2aff48e11f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']/option</value>
      <webElementGuid>b9ae5517-1ef1-43f6-b882-4eb2d09e659e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/following::option[1]</value>
      <webElementGuid>f98eb338-1543-4cf8-ae4a-27f5c6d94aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::option[1]</value>
      <webElementGuid>22086c8f-51ee-48ca-9491-0420695883dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::option[1]</value>
      <webElementGuid>7ada63d9-25a7-49e8-91c2-c939dd8f2985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::option[1]</value>
      <webElementGuid>4fd42693-4909-4c2c-8652-5823d1076344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agenzia test Sekurest']/parent::*</value>
      <webElementGuid>07508818-155f-42fc-9974-832f81b63683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select/option</value>
      <webElementGuid>ba749edc-4e26-4e1b-a5c0-1b65beb09d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-uhpatR2S69yjrp_2ejbBF-option-65a662ea9bb42500122eec55' and (text() = 'Agenzia test Sekurest' or . = 'Agenzia test Sekurest')]</value>
      <webElementGuid>ebe213a3-d5a4-45ce-aac7-682536c491d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
