<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Ariosto Ludovico</name>
   <tag></tag>
   <elementGuidId>3cedb6bf-b122-48c6-9224-656a73f0a6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-jq9AxjhPWd6pXq-pq5t-Z-option-667a8f8baee1f7050de3b953</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//option[contains(text(),'Ariosto Ludovico')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fa61b6bf-1ee1-43e9-b2e9-f12a2fd06a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-real-value</name>
      <type>Main</type>
      <value>&quot;667a8f8baee1f7050de3b953&quot;</value>
      <webElementGuid>cf6d6d32-1df2-41dd-89c9-cc233d48e600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-jq9AxjhPWd6pXq-pq5t-Z-option-667a8f8baee1f7050de3b953</value>
      <webElementGuid>6bd61bb4-d36e-4627-a53f-16ea242cea94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>667a8f8baee1f7050de3b953</value>
      <webElementGuid>25dae748-195d-4780-b606-067d436b3e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ariosto Ludovico</value>
      <webElementGuid>85992803-1cff-41de-9ead-5af687786a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-jq9AxjhPWd6pXq-pq5t-Z-option-667a8f8baee1f7050de3b953&quot;)</value>
      <webElementGuid>769b9f9d-cbcd-4167-96fc-325be548dd81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-jq9AxjhPWd6pXq-pq5t-Z-option-667a8f8baee1f7050de3b953']</value>
      <webElementGuid>283f2006-2a3d-4ced-93c3-aa8c8ff42ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-jq9AxjhPWd6pXq-pq5t-Z-available']/option[5]</value>
      <webElementGuid>a9466567-badd-4cec-a621-d491cd5acc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter available'])[1]/following::option[5]</value>
      <webElementGuid>90259f19-eed9-4396-8c39-1ad6790ea25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::option[5]</value>
      <webElementGuid>0b3beaa2-9dc7-4f28-8947-22bf8b9b60eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/preceding::option[186]</value>
      <webElementGuid>593a1020-a353-41d9-aa18-5deda20bfbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/preceding::option[186]</value>
      <webElementGuid>72fb7632-54d1-438b-989c-1d3039c7514a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ariosto Ludovico']/parent::*</value>
      <webElementGuid>610d21b5-a5ff-459d-9511-e1573c82745d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option[5]</value>
      <webElementGuid>65a847ef-48d1-4399-bcac-acd2e68b22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-jq9AxjhPWd6pXq-pq5t-Z-option-667a8f8baee1f7050de3b953' and (text() = 'Ariosto Ludovico' or . = 'Ariosto Ludovico')]</value>
      <webElementGuid>4048285b-95e9-4da2-9075-1eb25146a029</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
