<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Antonio Marco</name>
   <tag></tag>
   <elementGuidId>6a473d3f-91e2-406b-8e5d-920018e1900d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-bGzuTas50iaUSG1dKhIKQ-option-667a8f8caee1f7050de3b973</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//select//option[contains(text(),'Antonio Marco')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2add22a2-c4ce-4906-8be8-e29412139254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-real-value</name>
      <type>Main</type>
      <value>&quot;667a8f8caee1f7050de3b973&quot;</value>
      <webElementGuid>ce15e45e-6e61-4467-a2fc-f164157a8b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-bGzuTas50iaUSG1dKhIKQ-option-667a8f8caee1f7050de3b973</value>
      <webElementGuid>69e76f61-41bb-49b3-b087-949e9bac80bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>667a8f8caee1f7050de3b973</value>
      <webElementGuid>9374ebec-e3a6-410c-bc49-db588f5e47e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Antonio Marco</value>
      <webElementGuid>52900200-6835-4e43-b417-88d6623b3d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-bGzuTas50iaUSG1dKhIKQ-option-667a8f8caee1f7050de3b973&quot;)</value>
      <webElementGuid>fde25d65-8e6c-4347-a82e-7fa7470d50c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-bGzuTas50iaUSG1dKhIKQ-option-667a8f8caee1f7050de3b973']</value>
      <webElementGuid>8ca69d32-cab2-4599-ab8c-a7530e87fef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-bGzuTas50iaUSG1dKhIKQ-available']/option[6]</value>
      <webElementGuid>712507cb-0096-461e-8f4e-73c8a35d9e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter available'])[1]/following::option[6]</value>
      <webElementGuid>ddcfab4b-e213-4b48-8fdd-eae5d8cd9432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::option[6]</value>
      <webElementGuid>f89af5f4-cb39-40fb-bbde-b67f7168f578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/preceding::option[158]</value>
      <webElementGuid>cbdf6c3f-f6b5-4d7b-bf5f-1eb617f7b26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/preceding::option[158]</value>
      <webElementGuid>cd65c5fe-2201-4bd0-a4b2-c515746cf5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Antonio Marco']/parent::*</value>
      <webElementGuid>19a098ed-6828-4ad4-926e-e0431c1b2336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option[6]</value>
      <webElementGuid>afbe7b11-8253-4563-8df4-45de1a02f8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-bGzuTas50iaUSG1dKhIKQ-option-667a8f8caee1f7050de3b973' and (text() = 'Antonio Marco' or . = 'Antonio Marco')]</value>
      <webElementGuid>15534b27-25f3-4045-af0f-0de9d1b0d407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
