<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Agenzia Giorgia 1</name>
   <tag></tag>
   <elementGuidId>ebd18506-3cb9-4fc4-a17c-f7f395819fde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-bGzuTas50iaUSG1dKhIKQ-option-66422c1945e223d102364dac</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//select//option[contains(text(),'Agenzia Giorgia 1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7a68f549-b5c9-408f-9564-852bdc3a0d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70ff90b4-b4f8-4a4f-b0e0-145e476e63ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-real-value</name>
      <type>Main</type>
      <value>&quot;66422c1945e223d102364dac&quot;</value>
      <webElementGuid>f1053515-e199-4d75-bc04-4c5262622115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-bGzuTas50iaUSG1dKhIKQ-option-66422c1945e223d102364dac</value>
      <webElementGuid>d795b396-32c1-4ac2-bd77-ebc46e4a89e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>66422c1945e223d102364dac</value>
      <webElementGuid>e90c4138-22ea-4bd1-bdfc-18e5d037abfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenzia Giorgia 1</value>
      <webElementGuid>6661c29c-7820-4364-8238-17017c813cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-bGzuTas50iaUSG1dKhIKQ-option-66422c1945e223d102364dac&quot;)</value>
      <webElementGuid>5a373581-1aa4-4d4a-a752-32a0ca246f63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-bGzuTas50iaUSG1dKhIKQ-option-66422c1945e223d102364dac']</value>
      <webElementGuid>b1eb92a0-8ab4-4b02-8091-1ddcbec55d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-bGzuTas50iaUSG1dKhIKQ-available']/option[2]</value>
      <webElementGuid>69c227eb-7ac5-48d8-b8f4-580ae9dc9f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter available'])[1]/following::option[2]</value>
      <webElementGuid>e74bc271-f660-4040-a744-f97def373e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::option[2]</value>
      <webElementGuid>62da3785-3ff0-4581-b9f6-e6783992e6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/preceding::option[162]</value>
      <webElementGuid>e306d5b7-0785-4718-8d96-242658be7265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/preceding::option[162]</value>
      <webElementGuid>010b1e44-b03b-4a70-8d2d-39de2b8e9e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agenzia Giorgia 1']/parent::*</value>
      <webElementGuid>543c3bf0-aa84-4e93-a8f3-da84cda743e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select/option[2]</value>
      <webElementGuid>54fed227-86c1-427a-b504-f20c6d0c8dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-bGzuTas50iaUSG1dKhIKQ-option-66422c1945e223d102364dac' and (text() = 'Agenzia Giorgia 1' or . = 'Agenzia Giorgia 1')]</value>
      <webElementGuid>aa6de0eb-94c8-467d-933e-7cf52ba4a5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@id='rdl-uhpatR2S69yjrp_2ejbBF-option-66422c1945e223d102364dac']</value>
      <webElementGuid>c5907a2d-a0b1-45cd-94ba-17ab6cc0682d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']/option</value>
      <webElementGuid>e9a11508-38bc-4d71-b578-aa490b0dec84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/following::option[1]</value>
      <webElementGuid>bcd4e175-7495-494f-b3c2-d2b7ec4c2881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::option[1]</value>
      <webElementGuid>e696df91-1580-493a-bdc0-7daae4d2acc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::option[1]</value>
      <webElementGuid>9cbd0cd7-2e12-459f-97d1-f913e3eb458c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::option[1]</value>
      <webElementGuid>26f6121f-2559-4fcd-8452-d5e848fa60d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select/option</value>
      <webElementGuid>1baf5189-6be8-44da-9179-9b0b689cceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@id = 'rdl-uhpatR2S69yjrp_2ejbBF-option-66422c1945e223d102364dac' and (text() = 'Agenzia Giorgia 1' or . = 'Agenzia Giorgia 1')]</value>
      <webElementGuid>b4010089-9064-4e1a-81b5-164a6055d255</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
