<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agenzia test Sekurest</name>
   <tag></tag>
   <elementGuidId>7459a2b8-bf5f-4c93-ad3b-5ba3af817db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-uhpatR2S69yjrp_2ejbBF-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f23da70-cad2-4d7f-a8da-a777f3da07be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-control</value>
      <webElementGuid>fdc11b0a-6cd0-4e8b-8f8d-8a062379aa9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-uhpatR2S69yjrp_2ejbBF-selected</value>
      <webElementGuid>9c96b528-757d-4c55-9797-e9ebf61de3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenzia test Sekurest</value>
      <webElementGuid>6516dafc-8fe9-4315-84cf-ad536fb95889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-uhpatR2S69yjrp_2ejbBF-selected&quot;)</value>
      <webElementGuid>d5addc98-434a-46bd-8701-799f3ccd661c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']</value>
      <webElementGuid>083bfd14-3a7d-41fa-921a-3c3d56ec4b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-uhpatR2S69yjrp_2ejbBF']/div[3]/div[2]/select</value>
      <webElementGuid>960c1472-0300-4e3e-9e31-9fce714ef58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/following::select[1]</value>
      <webElementGuid>71b663a6-4836-490d-8a5a-06d67b7f77e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::select[1]</value>
      <webElementGuid>f7d7d768-9daa-44d4-90e4-752f306568af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::select[1]</value>
      <webElementGuid>2f3756a6-c19d-46b5-961a-cf7c7111437b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::select[1]</value>
      <webElementGuid>b42c8e33-ffe2-4c5b-aaec-10adf9e2f5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>cf7cef98-6335-4e93-8954-119a1ae2cded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rdl-uhpatR2S69yjrp_2ejbBF-selected' and (text() = 'Agenzia test Sekurest' or . = 'Agenzia test Sekurest')]</value>
      <webElementGuid>0eae7cd0-736c-4a69-bcff-7f7743be8d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
