<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agenzia Giorgia 1</name>
   <tag></tag>
   <elementGuidId>5d764cef-9110-488d-88d7-0addd118392f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-uhpatR2S69yjrp_2ejbBF-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1da4833b-dcd0-4367-ad86-71281b366d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-control</value>
      <webElementGuid>82013b34-7c17-40c9-b1bf-ade0823fdc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-uhpatR2S69yjrp_2ejbBF-selected</value>
      <webElementGuid>007c247c-f21a-4755-8b56-eb61348b662f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenzia Giorgia 1</value>
      <webElementGuid>501fbeb9-0a72-4e6b-9cc0-d0d6711f3d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-uhpatR2S69yjrp_2ejbBF-selected&quot;)</value>
      <webElementGuid>b3803628-fac1-47a1-a559-c62aa11d84ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rdl-uhpatR2S69yjrp_2ejbBF-selected']</value>
      <webElementGuid>322a3a63-b37c-4c34-8e97-4d984aa7475a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-uhpatR2S69yjrp_2ejbBF']/div[3]/div[2]/select</value>
      <webElementGuid>643cf443-70c1-48ab-b5d2-0100480ea8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/following::select[1]</value>
      <webElementGuid>88278602-c741-47f3-a015-d29ab273de14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::select[1]</value>
      <webElementGuid>8fcc3c52-0e8e-4b2f-8863-7536b2d6e7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::select[1]</value>
      <webElementGuid>7466dc15-8d11-4430-9183-a731de235acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::select[1]</value>
      <webElementGuid>b8b73f85-0523-4a06-a26f-c1b0459a6ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>e1a261e7-3aa4-4d83-bdbf-06b0ed911672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rdl-uhpatR2S69yjrp_2ejbBF-selected' and (text() = 'Agenzia Giorgia 1' or . = 'Agenzia Giorgia 1')]</value>
      <webElementGuid>4dc0f7db-073b-4e7f-a095-c3950a02e3b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
