<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Agenzia Giorgia 1Agenzia test Sekurest</name>
   <tag></tag>
   <elementGuidId>554ecbe7-3b0b-49d3-a686-3407441a68ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-4TkV9fApSIl3R1L7UyMDv-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rdl-4TkV9fApSIl3R1L7UyMDv-selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aea82eb6-0b6d-478a-87f8-63326c214aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-control</value>
      <webElementGuid>24377e2f-bbff-42b6-9b35-0379b1cf1838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-4TkV9fApSIl3R1L7UyMDv-selected</value>
      <webElementGuid>fe1cd0ea-6d9f-43d3-af28-904168272335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenzia Giorgia 1Agenzia test Sekurest</value>
      <webElementGuid>9b78c51f-e6f9-48b2-9278-a6c76ae2f044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-4TkV9fApSIl3R1L7UyMDv-selected&quot;)</value>
      <webElementGuid>a3850dc1-4210-4004-8a96-315a178f7330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rdl-4TkV9fApSIl3R1L7UyMDv-selected']</value>
      <webElementGuid>64af72c0-49c7-40bb-9bd7-7e0b4a6ea698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-4TkV9fApSIl3R1L7UyMDv']/div[3]/div[2]/select</value>
      <webElementGuid>a6e9f7a1-9a51-4df5-af20-ad9b21b6227e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/following::select[1]</value>
      <webElementGuid>ca1ce265-0827-4277-ac80-84d0d6fdf647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/following::select[1]</value>
      <webElementGuid>00fe21c1-6c5f-444d-8f72-baf0839bb1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi'])[1]/preceding::select[1]</value>
      <webElementGuid>97979f2a-c96e-464d-a5ec-e5bfd0a0872f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::select[1]</value>
      <webElementGuid>bc4f7ba3-4073-41e6-a856-9fdf2a2d2792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>ba0a297a-c797-4a27-9a61-d78755c43529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rdl-4TkV9fApSIl3R1L7UyMDv-selected' and (text() = 'Agenzia Giorgia 1Agenzia test Sekurest' or . = 'Agenzia Giorgia 1Agenzia test Sekurest')]</value>
      <webElementGuid>069263df-b870-401b-bdda-33a4e0d6148a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
