<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_adadadAgenzia Giorgia 1Agenzia Salva_98ce57</name>
   <tag></tag>
   <elementGuidId>64817190-eaa8-4845-8fac-a7a282d7efa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rdl-4TkV9fApSIl3R1L7UyMDv-available</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='rdl-4TkV9fApSIl3R1L7UyMDv-available']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a34c7ef-74d1-492c-9e3e-ad5a12b7df72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdl-control</value>
      <webElementGuid>d9e89874-8cdd-4832-bab3-f62be5283b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rdl-4TkV9fApSIl3R1L7UyMDv-available</value>
      <webElementGuid>4265deff-270c-4689-827d-becdad379848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adadadAgenzia Giorgia 1Agenzia Salvatore TestAntonio MarcoAriosto LudovicoArmenioBirobulkok1bulkok2CentroLibriCesare GiulioCliente di test IntegrazioneCLiente tCliente2°livelloClienteTest1°LivCustomer Test PadreCustomer Test Padre 2CustomerDiTestCustomerDiTestFiglioDaiomoDC_000DC_001DC_002DC_003DC_004DC_005DC_006DC_007DC_008DC_009DC_010DC_011DC_012DC_013DC_014DC_015DC_016DC_017DC_018DC_019DC_020DC_021DC_022DC_023DC_024DC_025DC_026DC_027DC_028DC_029DC_030DC_031DC_032DC_033DC_034DC_035DC_036DC_037DC_038DC_039DCBankEgitto CleopatraEremoEuronicsFastBankFClienteditstFerreroFerrero2FerreroSal2FerreroSal3Gabriele 3Gabriele 5Gabriele AverardiGabriele Averardi 3Gabriele Averardi2Gabriele1Gabriele2 testGallo SimonaGrosso MattiaMachiavelli NiccolòMitica MatildeMobilesoftNew ClientOmarPaolono AridonePaydoTestSalCompleteSalComplete2Salvatore testSamueleSekurestTestTest 2TEST EREDITA PADRETest eredità templateTEST SECONDO LIVELLOtest23testbulk1testbulk12testbulk2testbulk23testbulk3testbulk33testbulk35testbulk37testbulk38testbulk4testbulk40testbulk44testbulk5testbulk9testesecondolivelloERTestTestTestVIERI BOBO</value>
      <webElementGuid>5c5d011b-d84d-49cb-8ef6-8b1ccd9d56b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rdl-4TkV9fApSIl3R1L7UyMDv-available&quot;)</value>
      <webElementGuid>4ed0b6f3-9af7-41a6-8cb4-8d94a63c1781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='rdl-4TkV9fApSIl3R1L7UyMDv-available']</value>
      <webElementGuid>d2e10437-6463-421f-aa46-15eff892059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rdl-4TkV9fApSIl3R1L7UyMDv']/div/div[2]/select</value>
      <webElementGuid>105323cd-9a11-45aa-a93e-84bf467847b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter available'])[1]/following::select[1]</value>
      <webElementGuid>ddd23e67-7ae1-484b-a53c-c824f2de7526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::select[1]</value>
      <webElementGuid>8710ab67-32c0-4db4-9c7e-388bd9815c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected'])[1]/preceding::select[1]</value>
      <webElementGuid>17b3d863-5e66-427f-8da2-7e15670ea6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter selected'])[1]/preceding::select[1]</value>
      <webElementGuid>101f0009-52e0-44ed-92a8-5721b2914c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>377e9bad-094d-430e-99cb-734b6dfa42f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'rdl-4TkV9fApSIl3R1L7UyMDv-available' and (text() = 'adadadAgenzia Giorgia 1Agenzia Salvatore TestAntonio MarcoAriosto LudovicoArmenioBirobulkok1bulkok2CentroLibriCesare GiulioCliente di test IntegrazioneCLiente tCliente2°livelloClienteTest1°LivCustomer Test PadreCustomer Test Padre 2CustomerDiTestCustomerDiTestFiglioDaiomoDC_000DC_001DC_002DC_003DC_004DC_005DC_006DC_007DC_008DC_009DC_010DC_011DC_012DC_013DC_014DC_015DC_016DC_017DC_018DC_019DC_020DC_021DC_022DC_023DC_024DC_025DC_026DC_027DC_028DC_029DC_030DC_031DC_032DC_033DC_034DC_035DC_036DC_037DC_038DC_039DCBankEgitto CleopatraEremoEuronicsFastBankFClienteditstFerreroFerrero2FerreroSal2FerreroSal3Gabriele 3Gabriele 5Gabriele AverardiGabriele Averardi 3Gabriele Averardi2Gabriele1Gabriele2 testGallo SimonaGrosso MattiaMachiavelli NiccolòMitica MatildeMobilesoftNew ClientOmarPaolono AridonePaydoTestSalCompleteSalComplete2Salvatore testSamueleSekurestTestTest 2TEST EREDITA PADRETest eredità templateTEST SECONDO LIVELLOtest23testbulk1testbulk12testbulk2testbulk23testbulk3testbulk33testbulk35testbulk37testbulk38testbulk4testbulk40testbulk44testbulk5testbulk9testesecondolivelloERTestTestTestVIERI BOBO' or . = 'adadadAgenzia Giorgia 1Agenzia Salvatore TestAntonio MarcoAriosto LudovicoArmenioBirobulkok1bulkok2CentroLibriCesare GiulioCliente di test IntegrazioneCLiente tCliente2°livelloClienteTest1°LivCustomer Test PadreCustomer Test Padre 2CustomerDiTestCustomerDiTestFiglioDaiomoDC_000DC_001DC_002DC_003DC_004DC_005DC_006DC_007DC_008DC_009DC_010DC_011DC_012DC_013DC_014DC_015DC_016DC_017DC_018DC_019DC_020DC_021DC_022DC_023DC_024DC_025DC_026DC_027DC_028DC_029DC_030DC_031DC_032DC_033DC_034DC_035DC_036DC_037DC_038DC_039DCBankEgitto CleopatraEremoEuronicsFastBankFClienteditstFerreroFerrero2FerreroSal2FerreroSal3Gabriele 3Gabriele 5Gabriele AverardiGabriele Averardi 3Gabriele Averardi2Gabriele1Gabriele2 testGallo SimonaGrosso MattiaMachiavelli NiccolòMitica MatildeMobilesoftNew ClientOmarPaolono AridonePaydoTestSalCompleteSalComplete2Salvatore testSamueleSekurestTestTest 2TEST EREDITA PADRETest eredità templateTEST SECONDO LIVELLOtest23testbulk1testbulk12testbulk2testbulk23testbulk3testbulk33testbulk35testbulk37testbulk38testbulk4testbulk40testbulk44testbulk5testbulk9testesecondolivelloERTestTestTestVIERI BOBO')]</value>
      <webElementGuid>a2280735-b37c-4291-b7fa-a818c5e95ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
