<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Cerca gruppo per nome_Componente_11_1</name>
   <tag></tag>
   <elementGuidId>df1a086a-f733-42d7-b401-0b3c6ff7baca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Componente_11_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca gruppo per nome'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>036e8bf9-6a3b-4051-8250-35b02946eeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Componente_11_1</value>
      <webElementGuid>40cc925d-71d2-495c-a824-cffad89da8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Componente 11 \u2013 1</value>
      <webElementGuid>adadcb4f-9bd6-4dfe-a587-c975ec0516cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>723ef724-de0e-40b2-a97f-5c1d8b9ba94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>23.145</value>
      <webElementGuid>b81d465e-99b9-48c0-bd87-105ca67737cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>26.33</value>
      <webElementGuid>f5f6d0af-dd07-4c52-8098-3e235e50239a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 23.145 26.33</value>
      <webElementGuid>618e34fb-ed01-4fcf-963a-63711b1a3e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer w-1/12 inline-block</value>
      <webElementGuid>d895bf86-d38f-4004-9e28-da53b284f66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Componente_11_1&quot;)</value>
      <webElementGuid>1811dbcd-077b-420d-8230-5e8cb42d2d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca gruppo per nome'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>a9014d80-6039-4646-985c-2bb3cf83ef70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestione gruppi'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>bd74c186-4d22-4879-89f0-c792769f3a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>73e2348b-b9f0-43da-81a6-f4c1e0b5cc41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClienteTest1s'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>2054457b-d543-42a8-94a0-bd3056314584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'Componente_11_1']</value>
      <webElementGuid>65fbc6f7-1500-4f7e-b9a8-847247267a24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
