<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_ClienteTest1s</name>
   <tag></tag>
   <elementGuidId>53cad786-346f-4100-83ee-51314ab01e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.px-3.py-1.whitespace-nowrap.text-skin-base.font-regularMontserrat.text-base</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@class='bg-skin-bgPrimary h-14']//td[@role='cell'][contains(text(),'ClienteTest1s')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fb4064a6-e093-4a47-a201-29ca247c20cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>371c9d2d-377a-4bf9-a967-df928282100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> px-3 py-1 whitespace-nowrap text-skin-base font-regularMontserrat text-base</value>
      <webElementGuid>6997c6de-4cb9-4be5-9bf1-50a63b2d909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ClienteTest1s</value>
      <webElementGuid>f8ae5fa7-cc71-41bd-beea-a886ff98ef65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col h-screen justify-between font-regularMontserrat text-skin-base&quot;]/main[@class=&quot;mb-auto h-auto px-6 sm:px-10 xl:px-20 mt-28 py-6&quot;]/div[@class=&quot;flex py-6 xl:flex-row flex-col items-start space-y-16 xl:space-x-12&quot;]/div[@class=&quot;w-full xl:w-1/2 space-y-4&quot;]/div[@class=&quot;-mt-8 -pt-2&quot;]/div[@class=&quot;mt-2 flex flex-col&quot;]/div[@class=&quot;overflow-x-auto px-1 py-4&quot;]/div[@class=&quot;py-2 align-middle inline-block min-w-full relative&quot;]/table[@class=&quot;min-w-full table-auto px-2 text-skin-base relative&quot;]/tbody[@class=&quot;bg-white divide-y divide-skin-borderRowTable border border-skin-borderRowTable&quot;]/tr[@class=&quot;bg-skin-bgPrimary h-14&quot;]/td[@class=&quot;px-3 py-1 whitespace-nowrap text-skin-base font-regularMontserrat text-base&quot;]</value>
      <webElementGuid>8a73b730-4e5b-4b28-85be-73d9efae38ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div/div/div/div/table/tbody/tr/td</value>
      <webElementGuid>51aa0e39-624c-4e9e-b9e2-7e93975ab621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome'])[1]/following::td[1]</value>
      <webElementGuid>f5dd0165-7fcf-4e65-88e3-01fbe52dc392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca gruppo per nome'])[1]/following::td[1]</value>
      <webElementGuid>239b4345-21d1-4556-bbbd-fd722b82e4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementi per pagina'])[1]/preceding::td[2]</value>
      <webElementGuid>ec34473f-7af1-44b6-b51d-49a6e13043a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024'])[1]/preceding::td[2]</value>
      <webElementGuid>e95c486a-009b-4fbe-9a47-4097b1266e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ClienteTest1s']/parent::*</value>
      <webElementGuid>0c4785df-b1c5-4056-90db-ceb642cd4daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[@class='bg-skin-bgPrimary h-14']//td[@role='cell'][contains(text(),'ClienteTest1s')]</value>
      <webElementGuid>151dcf93-a3f2-403b-8c6e-b139a9335fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'ClienteTest1s' or . = 'ClienteTest1s')]</value>
      <webElementGuid>3f79492f-9752-464c-babb-77933670d0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
